// Generated by CoffeeScript 1.7.1
(function() {
  var Commit, Tree, fixtures, git, should;

  should = require('should');

  fixtures = require('./fixtures');

  git = require('../src');

  Commit = require('../src/commit');

  Tree = require('../src/tree');

  describe("Commit", function() {
    describe("#tree", function() {
      var repo, tree;
      repo = git("" + __dirname + "/fixtures/branched");
      tree = null;
      before(function(done) {
        return repo.commits("master", function(err, commits) {
          tree = commits[0].tree();
          return done(err);
        });
      });
      return it("passes a tree", function() {
        return tree.should.be.an["instanceof"](Tree);
      });
    });
    return describe("#parents", function() {
      var parent, parents, repo;
      repo = fixtures.branched;
      parents = null;
      parent = null;
      before(function(done) {
        return repo.commits("something", function(err, commits) {
          parents = commits[0].parents();
          parent = commits[1];
          return done(err);
        });
      });
      it("is an Array of Commits", function() {
        parents.should.be.an["instanceof"](Array);
        return parents[0].should.be.an["instanceof"](Commit);
      });
      return it("has the parent commit", function() {
        return parents[0].id.should.eql(parent.id);
      });
    });
  });

}).call(this);
