// Generated by CoffeeScript 1.7.1
(function() {
  var Config, GIT_CONFIG, GIT_CONFIG_DUPLICATE_KEYS, should;

  should = require('should');

  Config = require('../src/config');

  GIT_CONFIG = "user.name=John Doe\nuser.email=john.doe@git-scm.com\ncore.editor=pico";

  GIT_CONFIG_DUPLICATE_KEYS = "user.name=John Doe\nuser.email=john.doe@git-scm.com\ncore.editor=pico\nuser.email=john.doe@github.com\ncore.editor=emacs";

  describe("Config", function() {
    return describe("()", function() {
      describe("when there are no overlapping keys", function() {
        var config;
        config = new Config.Config('mock repo');
        config.parse(GIT_CONFIG);
        return it("read the keys and values", function() {
          config.items['user.name'].should.equal('John Doe');
          config.items['user.email'].should.equal('john.doe@git-scm.com');
          return config.items['core.editor'].should.equal('pico');
        });
      });
      return describe("with overlapping keys", function() {
        var config;
        config = new Config.Config('mock repo');
        config.parse(GIT_CONFIG_DUPLICATE_KEYS);
        return it("read the keys and values", function() {
          config.items['user.name'].should.equal('John Doe');
          config.items['user.email'].should.equal('john.doe@github.com');
          return config.items['core.editor'].should.equal('emacs');
        });
      });
    });
  });

}).call(this);
